export const basic_colors = [
  "#008bae",
  "#65318c",
  "#8bc442",
  "#e7262b",
  "#f59121",
  "#b92587",
];

export const colors = [
  "#008bae",
  "#65318c",
  "#8bc442",
  "#e7262b",
  "#f59121",
  "#b92587",
  "#278e45",
  "#0756a1",
];

export const traits_table = {
  leaf_mass_per_area_g_m2: "leaf_area_and_water_samples",
  leaf_dry_matter_content_mg_g: "leaf_area_and_water_samples",
  equivalent_water_thickness_cm: "leaf_area_and_water_samples",
  leaf_relative_water_content_perc: "leaf_area_and_water_samples",
  al_mg_g: "icp_leaf_element_concentrations",
  b_mg_g: "icp_leaf_element_concentrations",
  ca_mg_g: "icp_leaf_element_concentrations",
  cu_mg_g: "icp_leaf_element_concentrations",
  fe_mg_g: "icp_leaf_element_concentrations",
  k_mg_g: "icp_leaf_element_concentrations",
  mg_mg_g: "icp_leaf_element_concentrations",
  mn_mg_g: "icp_leaf_element_concentrations",
  mo_mg_g: "icp_leaf_element_concentrations",
  na_mg_g: "icp_leaf_element_concentrations",
  ni_mg_g: "icp_leaf_element_concentrations",
  p_mg_g: "icp_leaf_element_concentrations",
  s_mg_g: "icp_leaf_element_concentrations",
  zn_mg_g: "icp_leaf_element_concentrations",
  c_perc: "c_n_leaf_concentrations",
  n_perc: "c_n_leaf_concentrations",
  soluble_perc: "carbon_fractions_bags",
  cellulose_perc: "carbon_fractions_bags",
  hemicellulose_perc: "carbon_fractions_bags",
  lignin_perc: "carbon_fractions_bags",
  recalcitrants_perc: "carbon_fractions_bags",
  chla_mg_g_disk_mass: "pigments_extracts",
  chlb_mg_g_disk_mass: "pigments_extracts",
  carot_mg_g_disk_mass: "pigments_extracts",
  chl_a_chl_b_ratio: "pigments_extracts",
  chla_mg_m2: "pigments_extracts",
  chlb_mg_m2: "pigments_extracts",
  carot_mg_m2: "pigments_extracts",
};
